modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="xevaltansworld"
version="1.0.0"
displayName="Xevaltan'sWorld"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="noebo, MCreator"

[[dependencies.xevaltansworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



